# Database
DB_URL=jdbc:postgresql://gondola.proxy.rlwy.net:42857/railway?user=postgres&password=AFJqYeuofIfzdgtpfcsGTeMuKhKfDBkZ
DB_USERNAME=postgres
DB_PASSWORD=AFJqYeuofIfzdgtpfcsGTeMuKhKfDBkZ

# JWT
JWT_SECRET=yt5ku3RSf6/GPsh6DC0D+wIdJhbTQbmaAzqXOXUy/A99ynfNpvhqoyZ3hj3Pv7mMX2VCW10YVKEg2ENk1Sb2MQ==
JWT_EXPIRATION=900000
JWT_REFRESH_EXPIRATION=604800000

# Email
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=yoeurnkimsan@gmail.com
MAIL_PASSWORD=xnxfvtxghyjwuiwu
MAIL_SMTP_AUTH=true
MAIL_STARTTLS_ENABLE=true
MAIL_DEBUG=true

# Cache
CACHE_TYPE=caffeine
CACHE_SPEC=maximumSize=1000,expireAfterWrite=5m

# Base URL (local or production)
APP_BASE_URL=https://app.piggysaving.com

# Icons
APP_ICON_SENDER=https://cdn-icons-png.flaticon.com/256/13207/13207616.png
APP_ICON_RECEIVER=https://cdn-icons-png.flaticon.com/256/13207/13207616.png

# HMAC
QR_HMAC_SECRET=tdGhUFl0cOseg4WCmhElDth2STFv9fnxHUvTaP+MzC512AHehz5X+x81EB0KqgyukLdvdz8Nhlu1/Cw+k+//RA==

# Spring Profile (optional, you already set it via command line)
SPRING_PROFILES_ACTIVE=dev

#ALLOW ORIGIN CORS
ALLOW_ORIGIN = http://localhost:3000,https://wing-piggy-saving-final-uyp4.vercel.app
