spring.application.name=Piggy-Saving
spring.profiles.active=dev
# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Email Configuration (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yoeurnkimsan@gmail.com
spring.mail.password=xnxfvtxghyjwuiwu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Cache configuration for OTP storage
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=5m
#Show raw SMTP traffic
# Show raw SMTP traffic
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG


# Base URL
app.base-url=https://app.piggysaving.com

# Icon URLs (use your Flaticon URL)
app.icons.sender=https://cdn-icons-png.flaticon.com/256/13207/13207616.png
app.icons.receiver=https://cdn-icons-png.flaticon.com/256/13207/13207616.png
# Base URL for your application (change per environment)

# Optional: override individual links if they differ from base-url paths
app.links.goals=${app.base-url}/goals
app.links.wallet=${app.base-url}/wallet
app.links.transactions=${app.base-url}/transactions
app.links.unsubscribe=${app.base-url}/unsubscribe
app.links.privacy=${app.base-url}/privacyarrow
