spring.application.name=Piggy-Saving
spring.config.import=optional:file:./secrets.properties
spring.profiles.active=${SPRING_PROFILES_ACTIVE}   # or use -Dspring.profiles.active on the command line

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.debug=${MAIL_DEBUG:false}

# Cache
spring.cache.type=${CACHE_TYPE:caffeine}
spring.cache.caffeine.spec=${CACHE_SPEC:maximumSize=1000,expireAfterWrite=5m}

# Base URL
app.base-url=${APP_BASE_URL:https://app.piggysaving.com}

# Icons
app.icons.sender=${APP_ICON_SENDER:https://cdn-icons-png.flaticon.com/256/13207/13207616.png}
app.icons.receiver=${APP_ICON_RECEIVER:https://cdn-icons-png.flaticon.com/256/13207/13207616.png}

# Links (they use the base URL)
app.links.goals=${app.base-url}/goals
app.links.wallet=${app.base-url}/wallet
app.links.transactions=${app.base-url}/transactions
app.links.unsubscribe=${app.base-url}/unsubscribe
app.links.privacy=${app.base-url}/privacyarrow

# HMAC Secret
qr.hmac.secret=${QR_HMAC_SECRET}